### ISSUE TITLE
楼主你好，我发现计算文字size时，同一段文字在5s和6下都是一样的范围。最后发现是此时屏幕宽度打印出来都是320导致的。但最后文字又是适配不同机型的，请问这是怎么回事？

### ISSUE THREAD

**Issue by xuzhenhao** [hawk0620/PYQFeedDemo#1]
楼主你好，我发现计算文字size时，同一段文字在5s和6下都是一样的范围。最后发现是此时屏幕宽度打印出来都是320导致的。但最后文字又是适配不同机型的，请问这是怎么回事？

**Comment by hawk0620** [comment]
你好，文字是通过给定的宽度计算出高度的，具体方法是：- (CGSize)sizeWithConstrainedToWidth:fromFont:lineSpace:lineBreakMode:

而文字的宽度你可以看看定义在prefix.h里的宏定义：
#define kContentTextWidth (ScreenWidth - kAvatar - kSpec \* 2 - kTextGap)

至于打印出来的320，我不是很清楚你是如何打印的。
