### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by bmcciscoding** [hawk0620/PYQFeedDemo#2]
![97d113b1-73ea-44d4-9c82-bd74742ce3bb](https://cloud.githubusercontent.com/assets/20121334/18303695/f846a850-7510-11e6-9fab-33aa7ba21ddd.png)

用 Instrument 一跑，内存泄漏很多

**Comment by hawk0620** [comment]
我用模拟器在Instrument看到的leak主要是CTFramesetterCreateWithAttributedString这个引起的，按照下图说的：
![a03b7aa1-f9dd-4d0c-85d0-cb811b198b05](https://cloud.githubusercontent.com/assets/5633917/18500022/8fc0999c-7a76-11e6-8aa0-f63cb2e58feb.png)
当我用真机的时候就没看到泄露，如果是ViewController的push和pop，需要在页面消失前清理VideoPlayerManager单例：
VideoPlayerManager *manager = [VideoPlayerManager shareInstance];
manager = nil;
这样，使用MLeaksFinder检测也不会有内存泄漏。
